name: PetTrackCare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: any
  intl: any
  http: any
  fl_chart: any
  table_calendar: any
  qr_flutter: any
  flutter_map: any
  latlong2: any
  geocoding: ^4.0.0
  image_picker: ^1.0.5
  image: ^4.2.0
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  flutter_sound: ^9.2.13+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.1
  zego_uikit_prebuilt_call: ^4.17.9
  zego_uikit: ^2.28.22
  zego_uikit_signaling_plugin: ^2.8.15
  zego_plugin_adapter: ^2.13.9
  image_cropper: ^9.1.0
  realtime_client: ^2.5.1 
  flutter_local_notifications: ^19.4.0
  badges: ^3.1.2
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  app_settings: any
  android_intent_plus: any
  url_launcher: any
  universal_platform: any
  firebase_database: ^10.5.7
  flutter_ringtone_player: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - .env

dependency_overrides:
  sign_in_with_apple:
    path: ./fake_sign_in_with_apple
